services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pf-user-service
    ports:
      - "9000:9000"
    depends_on:
      - mysql
      - redis
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=secret
      - DB_NAME=user_service
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: ["app"] 

  mysql:
    image: mysql:8.0
    container_name: pf-user-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: user_service
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: pf-user-redis
    ports:
      - "6379:6379"

volumes:
  mysql_data:
